@baseUrl1 = http://localhost:4004/odata/v4

@baseUrl = http://localhost:4004




# Get Service Document
GET {{baseUrl}}/admin

###----------------------------
#test hello world
GET {{baseUrl1}}/hello/sayHello(name='World')

### ------------------------------------------------------------------------
# Get Service Metadata Document
GET {{baseUrl}}/admin/$metadata


### ------------------------------------------------------------------------
# Get all books with inlined author
GET {{baseUrl}}/admin/Books?$expand=author


### ------------------------------------------------------------------------
# Get all authors with inlined books
GET {{baseUrl}}/admin/Authors?$expand=books

### ------------------------------------------------------------------------
# Get all books with language en
# with inlined publication country and currency
GET {{baseUrl}}/admin/Books?$expand=publCountry,price_currency
Accept-Language: de


### ------------------------------------------------------------------------
# Get all books with language de
# with inlined publication country and currency
GET {{baseUrl}}/admin/Books?$expand=publCountry,price_currency
Accept-Language: de


### ------------------------------------------------------------------------
# Get all authors with language en
# with inlined epoch
GET {{baseUrl}}/admin/Authors?$expand=epoch
Accept-Language: en


### ------------------------------------------------------------------------
# Get all authors with language de
# with inlined epoch
GET {{baseUrl}}/admin/Authors?$expand=epoch


### ------------------------------------------------------------------------
# Create a new author with empty name and invalid epoch ID
POST {{baseUrl}}/admin/Authors
Content-Type: application/json

{
  "name": "",
  "dateOfBirth": "1759-11-10",
  "dateOfDeath": "1805-05-09",  
  "epoch": {"ID": 190}
}


### ------------------------------------------------------------------------
# Create a new book with empty title, invalid author ID and invalid genre
POST {{baseUrl}}/admin/Books
Content-Type: application/json

{
  "title": "",
  "author_ID": "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee",
  "genre": 3
}


### ------------------------------------------------------------------------
# Create a new book with empty title, invalid genre and without author
POST {{baseUrl}}/admin/Books
Content-Type: application/json

{
  "title": "",
  "genre": 3
}


### ------------------------------------------------------------------------
# Retrieve the ID of William Shakespeare
# Use this ID to create a new book with stock 0 (default)
# @name getShakespeare
GET {{baseUrl}}/admin/Authors?$filter=name eq 'William Shakespeare'

@authorID = {{getShakespeare.response.body.$.value[0].ID}}

###

POST {{baseUrl}}/admin/Books
Content-Type: application/json

{
  "title": "Macbeth",
  "author_ID": "{{authorID}}"
}

### ------------------------------------------------------------------------
# Create a new author
# ... and assign the ID of the newly created author to the variable authorID
#@name createNewAuthor

POST {{baseUrl}}/admin/Authors
Content-Type: application/json

{
  "name": "Initial Version"
}

###
@authorID = {{createNewAuthor.response.body.$.ID}}

## Read the newly created author for editing a first time
# ... and assign the received ETag to the variable ETag1
GET {{baseUrl}}/admin/Authors('ffdd2d3e-6604-427d-aca8-c08edafb0c71')

###
@ETag1 = {{createNewAuthor.response.headers.ETag}}


### Read the newly created author for editing a second time
# ... and assign the received ETag to the variable ETag2
GET {{baseUrl}}/admin/Authors('ffdd2d3e-6604-427d-aca8-c08edafb0c71')

###
@ETag2 = {{createNewAuthor.response.headers.ETag}}



#   ETag1 and Etag2 match because no changes have been made yet.



### ------------------------------------------------------------------------
# Update the newly created author using ETag1 received 
# when the Author was first read.
# The update implicitly creates a new ETag value.
PUT {{baseUrl}}/admin/Authors('ffdd2d3e-6604-427d-aca8-c08edafb0c71')
If-Match: {{ETag1}}
Content-Type: application/json

{
  "name": "Update 1 of Initial Version"
}



### ------------------------------------------------------------------------
# Try another update using ETag2 received
# when the author was read for the second time.
# This will fail with a HTTP status code 412 Precondition Failed.
PUT {{baseUrl}}/admin/Authors({{authorID}})
If-Match: {{ETag2}}
Content-Type: application/json

{
  "name": "Update 2 of Initial Version"
}


### ------------------------------------------------------------------------
# Get Service Document
GET {{baseUrl}}/cat


### ------------------------------------------------------------------------
# Get Service Metadata Document
GET {{baseUrl}}/cat/$metadata


### ------------------------------------------------------------------------
# Get all books with language en
GET {{baseUrl}}/cat/Books
Accept-Language: en


### ------------------------------------------------------------------------
# Get all books with language de
GET {{baseUrl}}/cat/Books
Accept-Language: de


### ------------------------------------------------------------------------
# Get all authors with language en
GET {{baseUrl}}/cat/Authors
Accept-Language: en


### ------------------------------------------------------------------------
# Get all authors with language de
GET {{baseUrl}}/cat/Authors
Accept-Language: de


### ------------------------------------------------------------------------
# Create a new author
POST {{baseUrl}}/cat/Authors
Content-Type: application/json

{
  "name": "Friedrich Schiller",
  "dateOfBirth": "1759-11-10",
  "dateOfDeath": "1805-05-09",
  "epoch": {"ID": 120}
}

###
GET {{baseUrl}}/admin/Authors('ffdd2d3e-6604-427d-aca8-c08edafb0c71')

@ETag2 = {{createNewAuthor.response.headers.ETag}}

@authorID = {{createNewAuthor.response.body.$.ID}}
### ------------------------------------------------------------------------
# Create a new author with error
PUT  {{baseUrl}}/admin/Authors({{authorID}})
If-Match: {{ETag2}}
Content-Type: application/json

{
  "name": "Update Author",
  "dateOfBirth": "1759-11-10",
  "dateOfDeath": "1605-05-09",

}

###

POST {{baseUrl}}/admin/Authors
Content-Type: application/json

{
  "name": "New Data Author",
  "dateOfBirth": "1759-11-10",
  "dateOfDeath": "1605-04-08",
  "epoch": {"ID": 120}
}


#d0a57b3e-9a66-42d8-9fea-749db58f98d1


### ----------------------Custom Action--------------------------------------------------
# Get Service Metadata Document
GET {{baseUrl}}/cat/$metadata



### ------------------------------------------------------------------------
# Retrieve the ID of the book with the title 'Faust'
# Use this ID to call the submitOrder action
# @name getBookID
GET {{baseUrl}}/cat/Books?$filter=title eq 'Faust'

###

@bookID = {{getBookID.response.body.$.value[0].ID}}

POST {{baseUrl}}/cat/submitOrder
Content-Type: application/json

{
  "book": "{{bookID}}",
  "quantity": 2
}



### ------------------------------------------------------------------------
# Call the submitOrder action with a quantity of 0 -> error
POST {{baseUrl}}/cat/submitOrder
Content-Type: application/json

{
  "book": "{{bookID}}",
  "quantity": 0
}

### ------------------------------------------------------------------------
# Call the submitOrder action with a quantity that exceeds stock -> error
POST {{baseUrl}}/cat/submitOrder
Content-Type: application/json

{
  "book": "{{bookID}}",
  "quantity": 999999
}



### ------------------------------------------------------------------------
# Call the submitOrder action with an invalid book ID -> error
POST {{baseUrl}}/cat/submitOrder
Content-Type: application/json

{
  "book": "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee",
  "quantity": 2
}

###

POST {{baseUrl}}/cat/submitOrder
Accept-Language: de
Content-Type: application/json

{
  "book": "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee",
  "quantity": 2
}





### ------------------------------------------------------------------------
# Create a new author using the admin service 
# with the date of death before the date of birth -> error
# Check the returned error message in German and in English (Accept-Language) 
POST {{baseUrl}}/admin/Authors
Accept-Language: en   
Content-Type: application/json

{
  "name": "Friedrich Schiller",
  "dateOfBirth": "1759-11-10",
  "dateOfDeath": "1705-05-09", 
  "epoch": {"ID": 120}
}

###

POST {{baseUrl}}/admin/Authors
Accept-Language: de 
Content-Type: application/json

{
  "name": "Friedrich Schiller",
  "dateOfBirth": "1759-11-10",
  "dateOfDeath": "1705-05-09", 
  "epoch": {"ID": 120}
}

############################################################################
############################################################################
## CATALOG SERVICE
############################################################################
############################################################################

### ------------------------------------------------------------------------
# Get all books - unauthenticated
GET {{baseUrl}}/cat/Books


### ------------------------------------------------------------------------
# Get all authors - unauthenticated
GET {{baseUrl}}/cat/Authors


### ------------------------------------------------------------------------
# Create a new author - unauthenticated
POST {{baseUrl}}/cat/Authors
Content-Type: application/json

{
  "name": "Friedrich Schiller",
  "dateOfBirth": "1759-11-10",
  "dateOfDeath": "1805-05-09",
  "epoch": {"ID": 120}
}


### ------------------------------------------------------------------------
# Create a new book with author William Shakespeare - unauthenticated
# @name getShakespeare
GET {{baseUrl}}/cat/Authors?$filter=name eq 'William Shakespeare'

###
@authorID = {{getShakespeare.response.body.$.value[0].ID}}


###
POST {{baseUrl}}/cat/Books
Content-Type: application/json

{
  "title": "Test Title",
  "author": { "ID": "{{authorID}}" }
}



### ------------------------------------------------------------------------
# Call the submitOrder action - unauthenticated and authenticated
# Retrieve the ID of the book with the title 'Faust'
# This ID is used to call the submitOrder action of the catalog service
# @name getBookID
GET {{baseUrl}}/cat/Books?$filter=title eq 'Faust'

###
@bookID = {{getBookID.response.body.$.value[0].ID}}


### ------------------------------------------------------------------------
# Call the submitOrder action - unauthenticated
POST {{baseUrl}}/cat/submitOrder
Content-Type: application/json

{
  "book": "{{bookID}}",
  "quantity": 2
}


### ------------------------------------------------------------------------
# Call the submitOrder action - authenticated
POST {{baseUrl}}/cat/submitOrder
Authorization: Basic catuser:abcd1234
Content-Type: application/json

{
  "book": "{{bookID}}",
  "quantity": 2
}




############################################################################
############################################################################
## ADMIN SERVICE
############################################################################
############################################################################

### ------------------------------------------------------------------------
# Get all books - as catuser
GET {{baseUrl}}/admin/Books
Authorization: Basic catuser:abcd1234


### ------------------------------------------------------------------------
# Get all books - as adminuser
GET {{baseUrl}}/admin/Books
Authorization: Basic adminuser:abcd1234


### ------------------------------------------------------------------------
# Create a new author - as catuser
POST {{baseUrl}}/admin/Authors
Authorization: Basic catuser:abcd1234
Content-Type: application/json

{
  "name": "Friedrich Schiller",
  "dateOfBirth": "1759-11-10",
  "dateOfDeath": "1805-05-09",
  "epoch": {"ID": 120}
}


### ------------------------------------------------------------------------
# Create a new author - as adminuser
POST {{baseUrl}}/admin/Authors
Authorization: Basic adminuser:abcd1234
Content-Type: application/json

{
  "name": "Friedrich Schiller",
  "dateOfBirth": "1759-11-10",
  "dateOfDeath": "1805-05-09",
  "epoch": {"ID": 120}
}



### ------------------------------------------------------------------------
# Delete a book without stock and a book with stock
# Read the ID of a book without stock
# @name getBookWithoutStock
GET {{baseUrl}}/admin/Books?$filter=stock eq 0&$top=1&$select=ID
Authorization: Basic adminuser:abcd1234

### Assign the received ID to the variable ID1
@ID1 = {{getBookWithoutStock.response.body.$.value[0].ID}}


### ------------------------------------------------------------------------
# Retrieve the ETag belonging to the read book
# @name getETag1
GET {{baseUrl}}/admin/Books({{ID1}})
Authorization: Basic adminuser:abcd1234

### Assign the received ETag to the variable ETag1
@ETag1 = {{getETag1.response.headers.ETag}}


### ------------------------------------------------------------------------
# Delete the corresponding book using the ID and the ETag retrieved above
DELETE {{baseUrl}}/admin/Books({{ID1}})
If-Match: {{ETag1}}
Authorization: Basic adminuser:abcd1234




### ------------------------------------------------------------------------
# Delete a book with stock 
# Read the ID of a book with stock
# @name getBookWithStock
GET {{baseUrl}}/admin/Books?$filter=stock gt 0&$top=1&$select=ID
Authorization: Basic adminuser:abcd1234

### Assign the received ID to the variable ID2
@ID2 = {{getBookWithStock.response.body.$.value[0].ID}}


### ------------------------------------------------------------------------
# Retrieve the ETag belonging to the read book
# @name getETag2
GET {{baseUrl}}/admin/Books({{ID2}})
Authorization: Basic adminuser:abcd1234

### Assign the received ETag to the variable ETag2
@ETag2 = {{getETag2.response.headers.ETag}}


### ------------------------------------------------------------------------
# Delete the corresponding book using the ID and the ETag retrieved above
DELETE {{baseUrl}}/admin/Books({{ID2}})
If-Match: {{ETag2}}
Authorization: Basic adminuser:abcd1234
